[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_helloworld = "HJRfF8vQs4SozB9MWGETrVm4HRvjndUM65MbkQW8RsYh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/kevin/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
